source: .
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
name: TracEE
url: http://tracee.io
highlighter: pygments
#description: TODO: A description for your blog
