source: .
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
name: TracEE
url: http://tracee.io

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript","tables", "with_toc_data"]


highlighter: pygments
#description: TODO: A description for your blog
